### ISSUE TITLE
Update Schedule for RBC Workshop + Speaker info

### ISSUE THREAD

**Issue by eharason** [cusec/2021#105]
Hi CUSEC! We've had some updates to the RBC Workshop + Speaker. Our speaker's last name was spelled wrong ;) Please see below. What do you think?

1. Workshop updates. 

`current:`
```
12:15 PM - 01:15 PM | Workshop by RBC
Analyzing a day in my Spotify life with technology
```
`to be updated to:`
12:15 PM - 01:15 PM | Andrew Briggs - Technical Lead at RBC
Practicing Architecture by analyzing a day in my Spotify life. Please read [GitHub repo](https://github.com/atbriggs/nsync) prior to Workshop!

2. Speaker updates:

`current:`
```
05:30 PM06:00 PM | Alexandra Cactus
```

`to be updated to:`
05:30 PM06:00 PM | Alex Catus - Fullstack Developer at RBC
Initiation to RxJs, a love story. [GitHub demo](https://github.com/alexCatus/rxjs-demo) available here!

**Comment by sttic** [comment]
On it! Thanks for letting us know :smile:
