### ISSUE TITLE
Rearrange/modify splash page mailing list and sponsor link items

### ISSUE THREAD

**Issue by sttic** [cusec/2021#25]
> Would it make sense to put "Join our email list" and the input box on the same line? And move the "Interested in sponsoring?" text to it's own line in Desktop?

> "Join our email listing" => "Join our email list" or "Join our mailing list"

https://cusec-team.slack.com/archives/C03KB4HCN/p1599061048000400?thread_ts=1598997168.005300&cid=C03KB4HCN

Currently:

![image](https://user-images.githubusercontent.com/20251243/92070486-26bdfe00-ed7a-11ea-8a6a-9edeaef75117.png)

---

It might be tricky finding a layout on desktop that makes the "Join our mailing list" message association clear while also not taking up too many lines.

**Comment by gordonpn** [comment]
Something I saw yesterday, Hackotberfest uses the button to let the user know the purpose of the action:

![Hacktoberfest - Laptop with HiDPI screen - 2020-3-9 at 9 28 43 AM](https://user-images.githubusercontent.com/4203037/92121206-0321a480-edc8-11ea-9369-2422e9ad6a45.jpg)

Maybe something we could consider? Our button would say something along the lines of "Join mailing list"

**Comment by sttic** [comment]
Definitely something to consider

> Our button would say something along the lines of "Join mailing list"

It'd look something like this:

![image](https://user-images.githubusercontent.com/20251243/92159528-90322100-edfb-11ea-8691-d73a7ebd0251.png)

Not bad imo, though the "Join mailing list" button might be a tad long with all that text

> Another idea I had was having a link/button that says "Join our mailing list". Upon clicking, a modal would show with the input and submit button. That would increase the user interaction to 2 clicks instead of 1, to sign up.

2 clicks for this isn't ideal but I think it's acceptable if the other options don't work out

**Comment by sttic** [comment]
Perhaps a long placeholder message with the font being small to keep the width reasonable?

https://hackthenorth.com/

![image](https://user-images.githubusercontent.com/20251243/92325825-8d157b80-f01b-11ea-94dd-cdf561725d42.png)

![image](https://user-images.githubusercontent.com/20251243/92325831-a4546900-f01b-11ea-980e-51d6cb4d06b0.png)

![image](https://user-images.githubusercontent.com/20251243/92325837-b1715800-f01b-11ea-8b2d-ae7ed81baef4.png)

**Comment by gordonpn** [comment]
> Perhaps a long placeholder message with the font being small to keep the width reasonable?

I don't mind that, so we can keep the arrow animation and all!
