### ISSUE TITLE
Add Code of Conduct and Privacy Policy

### ISSUE THREAD

**Issue by sttic** [cusec/2021#28]
Add Code of Conduct and Privacy Policy to their links in the footer.

Consider creating a separate page for them to link to so we're able to share it as links more easily.

- previous code of conduct: http://2020.cusec.net/#/codeofconduct
- previous privacy policy: N/A

**Comment by gordonpn** [comment]
Found some interesting generators:

Privacy Policy and Terms of Use: https://getterms.io/

Code of Conduct: https://miloslav.website/code-of-conduct/
